### ISSUE TITLE
Market Watcher: Poloniex exchange option crashes process

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#175]
### Expected behaviour

![market_watcher_expected](https://cloud.githubusercontent.com/assets/8068/26592872/62d1d1fa-4562-11e7-81a3-bd8067235d20.png)

### Actual behaviour

**Images are broken. Candles / charts do not load.**

![market_watcher_actual](https://cloud.githubusercontent.com/assets/8068/26592122/1ba25f40-4560-11e7-93fc-dba3d398b776.png)

***

**Process crashes with following logs.**

```
/Users/Oliver/GitHub/LiskHQ/lisk-explorer/lib/api/candles.js:89
                    last      : statistics.last ? statistics.last.close : results[1].close,
                                                                                    ^

TypeError: Cannot read property 'close' of undefined
    at /Users/Oliver/GitHub/LiskHQ/lisk-explorer/lib/api/candles.js:89:85
    at /Users/Oliver/GitHub/LiskHQ/lisk-explorer/node_modules/async/dist/async.js:3838:9
    at /Users/Oliver/GitHub/LiskHQ/lisk-explorer/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/Oliver/GitHub/LiskHQ/lisk-explorer/node_modules/async/dist/async.js:998:13)
    at /Users/Oliver/GitHub/LiskHQ/lisk-explorer/node_modules/async/dist/async.js:906:16
    at /Users/Oliver/GitHub/LiskHQ/lisk-explorer/node_modules/async/dist/async.js:3835:13
    at /Users/Oliver/GitHub/LiskHQ/lisk-explorer/lib/api/candles.js:70:32
    at Command.callback (/Users/Oliver/GitHub/LiskHQ/lisk-explorer/lib/candles/abstract.js:198:24)
    at normal_reply (/Users/Oliver/GitHub/LiskHQ/lisk-explorer/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/Users/Oliver/GitHub/LiskHQ/lisk-explorer/node_modules/redis/index.js:819:9)
```

### Steps to reproduce

Open the Market Watcher page with Poloniex option selected.

**Comment by karmacoma** [comment]
Probably related to this error raised when rebuilding candles:

```
lisk@explorer:~/lisk-explorer$ grunt candles:build 
Running "candles:build" task
Candles: Building minute candles for poloniex...
Candles: Retrieving trades from poloniex...
>> Error retrieving trades: Please specify a time window of no more than 1 year.
Warning: Task "candles:build" failed. Used --force, continuing.

Done, but with warnings.
```

See: https://github.com/LiskHQ/lisk-explorer/blob/development/lib/candles/poloniex.js#L18
