### ISSUE TITLE
Unstable Jenkins e2e test phase

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#394]
The end to end Protractor test phase breaks often on the CI server.
The problem is not reproducible on a local environment.

```
[12:11:48] E/launcher - waiting for element '.last-block-loaded'
Wait timed out after 4005ms
[12:11:48] E/launcher - TimeoutError: waiting for element '.last-block-loaded'
Wait timed out after 4005ms
    at WebDriverError (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/error.js:27:5)
    at TimeoutError (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/error.js:238:5)
    at /home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/promise.js:2107:17
    at ManagedPromise.invokeCallback_ (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: waiting for element '.last-block-loaded'
    at scheduleWait (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/promise.js:2094:20)
    at ControlFlow.wait (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/promise.js:2408:12)
    at Driver.wait (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/selenium-webdriver/lib/webdriver.js:943:29)
    at run (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/protractor/lib/browser.ts:66:27)
    at ProtractorBrowser.to.(anonymous function) [as wait] (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/node_modules/protractor/lib/browser.ts:74:12)
    at World.Then (/home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/features/step_definitions/generic.step.js:125:11)
[12:11:48] E/launcher - Process exited with error code 199

npm ERR! Linux 4.4.0-109-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "e2e-test" "--" "--params.baseURL" "http://localhost:6042"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! lisk-explorer@1.4.1 e2e-test: `protractor protractor.conf.js "--params.baseURL" "http://localhost:6042"`
npm ERR! Exit status 199
npm ERR! 
npm ERR! Failed at the lisk-explorer@1.4.1 e2e-test script 'protractor protractor.conf.js "--params.baseURL" "http://localhost:6042"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lisk-explorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor protractor.conf.js "--params.baseURL" "http://localhost:6042"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lisk-explorer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lisk-explorer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lisk/workspace/lisk-explorer_PR-388-PFI622ZPDPDNWKWYG4W7Z2LOYSDVM5DLQKSWYYMDZZXYPS3QFIEA/npm-debug.log
```

**Comment by MichalTuleja** [comment]
It looks like some elements are not visible during the test. 
It may be caused by a small size of Xvfb window - some elements of the responsive template may be not visible in low resolution.

**Comment by karmacoma** [comment]
Please disable the e2e tests in Jenkins for now and reference this issue, but do not close it.
