### ISSUE TITLE
Prevent Explorer from connecting to a 0.9 node

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#516]
### Expected behavior
The Explorer with an incompatible API should not connect to a node and log it appropriately.

### Actual behavior
Currently, any attempt to connect to a node compatible with 0.9 API breaks the process with a message similar to this:
```
/Users/michal/work/lisk-explorer/node_modules/async/dist/async.js:955
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /Users/michal/work/lisk-explorer/node_modules/async/dist/async.js:955:32
    at /Users/michal/work/lisk-explorer/node_modules/async/dist/async.js:3871:13
```

### Steps to reproduce
Connect to a 0.9 node.

**Comment by MichalTuleja** [comment]
Observed points of failure:

```
/Users/michal/work/lisk-explorer/node_modules/async/dist/async.js:955
        if (fn === null) throw new Error("Callback was already called.");
                         ^
Error: Callback was already called.
    at /Users/michal/work/lisk-explorer/node_modules/async/dist/async.js:955:32
    at /Users/michal/work/lisk-explorer/node_modules/async/dist/async.js:3871:13
    at blocks.getBlockStatus (/Users/michal/work/lisk-explorer/sockets/header.js:54:44)
    at Request.request.get [as _callback] (/Users/michal/work/lisk-explorer/lib/api/blocks.js:304:13)
    at Request.self.callback (/Users/michal/work/lisk-explorer/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/michal/work/lisk-explorer/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
```
