### ISSUE TITLE
Backend stability issues

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#529]
General ticket for all stability issues.

- [x] Delegate Monitor lastBlockDelegate <- occurs when the network is not forging
```
/Users/michal/work/lisk-explorer/sockets/delegateMonitor.js:201
                                        username: lastBlockDelegate.username,
                                                                   ^

TypeError: Cannot read property 'username' of undefined
    at async.waterfall (/Users/michal/work/lisk-explorer/sockets/delegateMonitor.js:201:33)
```

**Comment by MichalTuleja** [comment]
Another error, this time related to DNS library. 

```
lisk-explorer_1           | dns.js:236
lisk-explorer_1           |       throw new Error('"name" argument must be a string');
lisk-explorer_1           |       ^
lisk-explorer_1           |
lisk-explorer_1           | Error: "name" argument must be a string
lisk-explorer_1           |     at Object.query [as reverse] (dns.js:236:13)
lisk-explorer_1           |     at getHostName (/home/lisk/lisk-explorer/lib/api/statistics.js:189:8)
lisk-explorer_1           |     at /home/lisk/lisk-explorer/lib/api/statistics.js:206:27
lisk-explorer_1           |     at /home/lisk/lisk-explorer/node_modules/async/dist/async.js:3866:24
lisk-explorer_1           |     at eachOfArrayLike (/home/lisk/lisk-explorer/node_modules/async/dist/async.js:1055:9)
lisk-explorer_1           |     at eachOf (/home/lisk/lisk-explorer/node_modules/async/dist/async.js:1103:5)
lisk-explorer_1           |     at _parallel (/home/lisk/lisk-explorer/node_modules/async/dist/async.js:3865:5)
lisk-explorer_1           |     at Object.parallelLimit [as parallel] (/home/lisk/lisk-explorer/node_modules/async/dist/async.js:3948:5)
lisk-explorer_1           |     at getLocation (/home/lisk/lisk-explorer/lib/api/statistics.js:204:10)
lisk-explorer_1           |     at Locator.locate (/home/lisk/lisk-explorer/lib/api/statistics.js:231:11)
lisk-explorer_1           | dns.js:236
lisk-explorer_1           |       throw new Error('"name" argument must be a string');
lisk-explorer_1           |       ^
```
