### ISSUE TITLE
Invalid reverse DNS query crashes the process

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#540]
### Expected behavior
Invalid DNS query returns an IP in the `.unknown` domain.

### Actual behavior
Invalid DNS query crashes the process.

### Steps to reproduce
Hard to reproduce on production, but easy to simulate having access to the source code.
Change the line `lib/api/statistics.js:191` in the function  `Locator.getHostName` with the following pattern:
`dns.reverse(ip,` -> `dns.reverse('',`

**Comment by MichalTuleja** [comment]
Stack trace: 
```
lisk-explorer_1           | dns.js:236
lisk-explorer_1           |       throw new Error('"name" argument must be a string');
lisk-explorer_1           |       ^
lisk-explorer_1           |
lisk-explorer_1           | Error: "name" argument must be a string
lisk-explorer_1           |     at Object.query [as reverse] (dns.js:236:13)
lisk-explorer_1           |     at getHostName (/home/lisk/lisk-explorer/lib/api/statistics.js:189:8)
lisk-explorer_1           |     at /home/lisk/lisk-explorer/lib/api/statistics.js:206:27
lisk-explorer_1           |     at /home/lisk/lisk-explorer/node_modules/async/dist/async.js:3866:24
lisk-explorer_1           |     at eachOfArrayLike (/home/lisk/lisk-explorer/node_modules/async/dist/async.js:1055:9)
lisk-explorer_1           |     at eachOf (/home/lisk/lisk-explorer/node_modules/async/dist/async.js:1103:5)
lisk-explorer_1           |     at _parallel (/home/lisk/lisk-explorer/node_modules/async/dist/async.js:3865:5)
lisk-explorer_1           |     at Object.parallelLimit [as parallel] (/home/lisk/lisk-explorer/node_modules/async/dist/async.js:3948:5)
lisk-explorer_1           |     at getLocation (/home/lisk/lisk-explorer/lib/api/statistics.js:204:10)
lisk-explorer_1           |     at Locator.locate (/home/lisk/lisk-explorer/lib/api/statistics.js:231:11)
lisk-explorer_1           | dns.js:236
lisk-explorer_1           |       throw new Error('"name" argument must be a string');
lisk-explorer_1           |       ^
```
