### ISSUE TITLE
Market Watcher: Error while processing an invalid response from Bittrex/Poloniex

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#597]
Another problem found during regular updates to the Market Watcher.

```
lisk-explorer_1           | /home/lisk/lisk-explorer/lib/candles/abstract.js:87
lisk-explorer_1           |                                             logger.info(['Candles:', (start ? start.toString() : 'N/A'), 'to', (end ? end.toString() : 'N/A'), '=> Found', data.length.toString(), 'trades'].join(' '));
lisk-explorer_1           |                                                                                                                                                                       ^
lisk-explorer_1           |
lisk-explorer_1           | TypeError: Cannot read property 'toString' of undefined
lisk-explorer_1           |     at Request.request.get.jsonError [as _callback] (/home/lisk/lisk-explorer/lib/candles/abstract.js:87:129)
lisk-explorer_1           |     at Request.self.callback (/home/lisk/lisk-explorer/node_modules/request/request.js:186:22)
lisk-explorer_1           |     at emitTwo (events.js:106:13)
lisk-explorer_1           |     at Request.emit (events.js:191:7)
lisk-explorer_1           |     at Request.<anonymous> (/home/lisk/lisk-explorer/node_modules/request/request.js:1163:10)
lisk-explorer_1           |     at emitOne (events.js:96:13)
lisk-explorer_1           |     at Request.emit (events.js:188:7)
lisk-explorer_1           |     at IncomingMessage.<anonymous> (/home/lisk/lisk-explorer/node_modules/request/request.js:1085:12)
lisk-explorer_1           |     at IncomingMessage.g (events.js:292:16)
lisk-explorer_1           |     at emitNone (events.js:91:20)
lisk-explorer_1           |     at IncomingMessage.emit (events.js:185:7)
```

**Comment by MichalTuleja** [comment]
```
/Users/michal/work/lisk-explorer/lib/candles/abstract.js:87
						logger.info(['Candles:', (start ? start.toString() : 'N/A'), 'to', (end ? end.toString() : 'N/A'), '=> Found', data.length.toString(), 'trades'].join(' '));
						                                                                                                                          ^
TypeError: Cannot read property 'toString' of undefined
    at Request.__dirname.AbstractCandles.client.retrieveTrades.async.doUntil.request.get.jsonError [as _callback] (/Users/michal/work/lisk-explorer/lib/candles/abstract.js:87:129)
    at Request.init.self.callback (/Users/michal/work/lisk-explorer/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/michal/work/lisk-explorer/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/michal/work/lisk-explorer/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Comment by MichalTuleja** [comment]
```
1|explorer | TypeError: data.reverse is not a function
1|explorer |     at BittrexCandles.acceptTrades (/home/michal/lisk-explorer/lib/candles/bittrex.js:71:30)
1|explorer |     at Request.request.get.jsonError [as _callback] (/home/michal/lisk-explorer/lib/candles/abstract.js:96:22)
1|explorer |     at Request.self.callback (/home/michal/lisk-explorer/node_modules/request/request.js:185:22)
1|explorer |     at emitTwo (events.js:106:13)
1|explorer |     at Request.emit (events.js:191:7)
1|explorer |     at Request.<anonymous> (/home/michal/lisk-explorer/node_modules/request/request.js:1157:10)
1|explorer |     at emitOne (events.js:96:13)
1|explorer |     at Request.emit (events.js:188:7)
1|explorer |     at IncomingMessage.<anonymous> (/home/michal/lisk-explorer/node_modules/request/request.js:1079:12)
1|explorer |     at IncomingMessage.g (events.js:292:16)
```
